name: Continuous Integration

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      NEXT_PUBLIC_CONVEX_URL: ${{secrets.NEXT_PUBLIC_CONVEX_URL}}
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}}


    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.11.1'

      - name: Install dependencies
        run: npm install

      - name: Run format check
        run: npm run format

      - name: Run tests
        run: npm run test:ci

      - name: Generate Convex types
        run: npx convex codegen

      - name: TypeScript type codegen
        run: npx tsc --noEmit

      - name: Run Build
        run: npm run build