name: Vercel Production Deployment

env:
    VERCEL_ORG_ID: ${{secrets.VERCEL_ORG_ID}}
    VERCEL_PROJECT_ID: ${{secrets.VERCEL_PROJECT_ID}}

on:
    push:
        branches:
            - main
            - prod

jobs:
    deploy-dev:
        if: github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
                
            - name: Install Vercel CLI
              run: npm install --global vercel

            - name: Pull Vercel Environment (Development)
              run: vercel pull --yes --environment=preview --token=${{secrets.VERCEL_TOKEN}}

            - name: Build Project Artefacts(Development)
              run: vercel build --prod --token=${{secrets.VERCEL_TOKEN}}

            - name: Deploy Project Artefacts(Development)
              run: vercel deploy --prebuilt --prod --token=${{secrets.VERCEL_TOKEN}}

    deploy-prod:
        if: github.ref == 'refs/heads/prod'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
                
            - name: Install Vercel CLI
              run: npm install --global vercel

            - name: Pull Vercel Environment (Production)
              run: vercel pull --yes --environment=production --token=${{secrets.VERCEL_TOKEN}}

            - name: Build Project Artefacts(Production)
              run: vercel build --prod --token=${{secrets.VERCEL_TOKEN}}

            - name: Deploy Project Artefacts(Production)
              run: vercel deploy --prebuilt --prod --token=${{secrets.VERCEL_TOKEN}}